#! /usr/bin/env ruby

$LOAD_PATH << './lib'
require 'chess'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = 'Usage: chess [options]'

  opts.on('--white') do |_v|
    options[:color] = :white
  end

  opts.on('--black') do |_v|
    options[:color] = :black
  end
end.parse!

Chess::Engine::Shell.new(options).start!
